// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/inventory/v1/resources.proto

package v1

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// NodeResources reports node inventory details
type NodeResources struct {
	CPU                 CPU          `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu" yaml:"cpu"`
	Memory              Memory       `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory" yaml:"memory"`
	GPU                 GPU          `protobuf:"bytes,3,opt,name=gpu,proto3,castrepeated=GPUs" json:"gpu" yaml:"gpu"`
	EphemeralStorage    ResourcePair `protobuf:"bytes,4,opt,name=ephemeral_storage,json=ephemeralStorage,proto3" json:"ephemeral_storage" yaml:"ephemeral_storage"`
	VolumesAttached     ResourcePair `protobuf:"bytes,5,opt,name=volumes_attached,json=volumesAttached,proto3" json:"volumes_attached" yaml:"volumes_attached"`
	VolumesMounted      ResourcePair `protobuf:"bytes,6,opt,name=volumes_mounted,json=volumesMounted,proto3" json:"volumes_mounted" yaml:"volumes_mounted"`
	Version             string       `protobuf:"bytes,7,opt,name=version,proto3" json:"version" yaml:"version"`
	Bandwidth           string       `protobuf:"bytes,8,opt,name=bandwidth,proto3" json:"bandwidth" yaml:"bandwidth"`
	Os                  string       `protobuf:"bytes,9,opt,name=os,proto3" json:"os" yaml:"os"`
	Arch                string       `protobuf:"bytes,10,opt,name=arch,proto3" json:"arch" yaml:"arch"`
	CudaVersion         string       `protobuf:"bytes,11,opt,name=cuda_version,json=cudaVersion,proto3" json:"cuda_version" yaml:"cuda_version"`
	NvidiaDriverVersion string       `protobuf:"bytes,12,opt,name=nvidia_driver_version,json=nvidiaDriverVersion,proto3" json:"nvidia_driver_version" yaml:"nvidia_driver_version"`
}

func (m *NodeResources) Reset()         { *m = NodeResources{} }
func (m *NodeResources) String() string { return proto.CompactTextString(m) }
func (*NodeResources) ProtoMessage()    {}
func (*NodeResources) Descriptor() ([]byte, []int) {
	return fileDescriptor_f20a722bd8ee01b5, []int{0}
}
func (m *NodeResources) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NodeResources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NodeResources.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NodeResources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeResources.Merge(m, src)
}
func (m *NodeResources) XXX_Size() int {
	return m.Size()
}
func (m *NodeResources) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeResources.DiscardUnknown(m)
}

var xxx_messageInfo_NodeResources proto.InternalMessageInfo

func (m *NodeResources) GetCPU() CPU {
	if m != nil {
		return m.CPU
	}
	return CPU{}
}

func (m *NodeResources) GetMemory() Memory {
	if m != nil {
		return m.Memory
	}
	return Memory{}
}

func (m *NodeResources) GetGPU() GPU {
	if m != nil {
		return m.GPU
	}
	return GPU{}
}

func (m *NodeResources) GetEphemeralStorage() ResourcePair {
	if m != nil {
		return m.EphemeralStorage
	}
	return ResourcePair{}
}

func (m *NodeResources) GetVolumesAttached() ResourcePair {
	if m != nil {
		return m.VolumesAttached
	}
	return ResourcePair{}
}

func (m *NodeResources) GetVolumesMounted() ResourcePair {
	if m != nil {
		return m.VolumesMounted
	}
	return ResourcePair{}
}

func (m *NodeResources) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *NodeResources) GetBandwidth() string {
	if m != nil {
		return m.Bandwidth
	}
	return ""
}

func (m *NodeResources) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *NodeResources) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

func (m *NodeResources) GetCudaVersion() string {
	if m != nil {
		return m.CudaVersion
	}
	return ""
}

func (m *NodeResources) GetNvidiaDriverVersion() string {
	if m != nil {
		return m.NvidiaDriverVersion
	}
	return ""
}

func init() {
	proto.RegisterType((*NodeResources)(nil), "akash.inventory.v1.NodeResources")
}

func init() {
	proto.RegisterFile("akash/inventory/v1/resources.proto", fileDescriptor_f20a722bd8ee01b5)
}

var fileDescriptor_f20a722bd8ee01b5 = []byte{
	// 711 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x4d, 0x6b, 0xdb, 0x48,
	0x1c, 0xc6, 0x2d, 0xdb, 0xeb, 0xac, 0xc7, 0x79, 0xf1, 0x2a, 0xbb, 0x1b, 0x11, 0xb2, 0x1e, 0x33,
	0xcb, 0x42, 0x16, 0x1a, 0x9b, 0xa4, 0x85, 0x42, 0x6e, 0xb1, 0xdb, 0x84, 0x52, 0x92, 0x1a, 0xa5,
	0xce, 0xa1, 0x10, 0xcc, 0x44, 0x9a, 0xca, 0x22, 0xb1, 0x46, 0x8c, 0x5e, 0x4a, 0xbe, 0x41, 0x4f,
	0xa5, 0xd0, 0x4b, 0x3f, 0x43, 0x3f, 0x44, 0xcf, 0x39, 0xe6, 0xd8, 0xd3, 0xb4, 0x38, 0x37, 0x1d,
	0xf5, 0x09, 0x8a, 0x67, 0x46, 0x76, 0x1c, 0xbb, 0x21, 0x37, 0xcf, 0xff, 0x79, 0x9e, 0xdf, 0xff,
	0xd1, 0x60, 0x09, 0x20, 0x7c, 0x8e, 0x83, 0x7e, 0xd3, 0xf5, 0x62, 0xe2, 0x85, 0x94, 0x5d, 0x36,
	0xe3, 0xed, 0x26, 0x23, 0x01, 0x8d, 0x98, 0x45, 0x82, 0x86, 0xcf, 0x68, 0x48, 0x75, 0x5d, 0x78,
	0x1a, 0x63, 0x4f, 0x23, 0xde, 0x5e, 0xff, 0xd3, 0xa1, 0x0e, 0x15, 0x72, 0x73, 0xf4, 0x4b, 0x3a,
	0xd7, 0x37, 0xe6, 0xd0, 0x2c, 0x3f, 0xba, 0x47, 0x75, 0xc6, 0x2a, 0x9c, 0xa3, 0x0e, 0xc8, 0x60,
	0xb4, 0x4f, 0x1a, 0xfe, 0xbb, 0xa7, 0xaa, 0x8f, 0x5d, 0x26, 0x6d, 0xe8, 0x6b, 0x19, 0x2c, 0x1d,
	0x51, 0x9b, 0x98, 0xd9, 0x53, 0xe8, 0x2f, 0x41, 0xc1, 0xf2, 0x23, 0x43, 0xab, 0x6b, 0x9b, 0x95,
	0x9d, 0xb5, 0xc6, 0xec, 0xd3, 0x34, 0xda, 0x9d, 0x6e, 0xab, 0x7e, 0xc5, 0x61, 0x6e, 0xc8, 0x61,
	0xa1, 0xdd, 0xe9, 0x26, 0x1c, 0x8e, 0x22, 0x29, 0x87, 0xe0, 0x12, 0x0f, 0x2e, 0x76, 0x91, 0xe5,
	0x47, 0xc8, 0x1c, 0x8d, 0xf4, 0x53, 0x50, 0x92, 0xad, 0x8c, 0xbc, 0xe0, 0xad, 0xcf, 0xe3, 0x1d,
	0x0a, 0x47, 0xeb, 0x7f, 0x85, 0x2c, 0xc9, 0x73, 0xc2, 0xa1, 0xca, 0xa6, 0x1c, 0x2e, 0x49, 0xb0,
	0x3c, 0x23, 0x53, 0x09, 0xfa, 0x31, 0x28, 0x38, 0x7e, 0x64, 0x14, 0x7e, 0xdd, 0xf5, 0xa0, 0xd3,
	0x6d, 0x6d, 0x66, 0x5d, 0x0f, 0x64, 0x57, 0xe7, 0x76, 0x57, 0xc7, 0x8f, 0xd0, 0x97, 0xef, 0xb0,
	0x78, 0xd0, 0xe9, 0x06, 0xe6, 0x48, 0xd2, 0x3f, 0x6b, 0xe0, 0x0f, 0xe2, 0xf7, 0xc9, 0x80, 0x30,
	0x7c, 0xd1, 0x0b, 0x42, 0xca, 0xb0, 0x43, 0x8c, 0xa2, 0xd8, 0x51, 0x9f, 0xb7, 0x23, 0xbb, 0xbb,
	0x0e, 0x76, 0x59, 0xeb, 0x85, 0x5a, 0x56, 0x7d, 0x9e, 0x21, 0x8e, 0x25, 0x21, 0xe1, 0x70, 0x16,
	0x9b, 0x72, 0x68, 0xc8, 0x1e, 0x33, 0x12, 0x32, 0xab, 0xe4, 0x0e, 0x42, 0xff, 0xa4, 0x81, 0x6a,
	0x4c, 0x2f, 0xa2, 0x01, 0x09, 0x7a, 0x38, 0x0c, 0xb1, 0xd5, 0x27, 0xb6, 0xf1, 0xdb, 0x03, 0x9b,
	0xed, 0xab, 0x66, 0x2b, 0x27, 0x92, 0xb0, 0xa7, 0x00, 0x09, 0x87, 0x33, 0xd0, 0x94, 0xc3, 0x35,
	0xd9, 0xeb, 0xae, 0x82, 0xcc, 0x95, 0x78, 0x3a, 0xaf, 0x7f, 0xd0, 0x40, 0x36, 0xeb, 0x0d, 0x68,
	0xe4, 0x85, 0xc4, 0x36, 0x4a, 0x0f, 0x2c, 0xd5, 0x56, 0xa5, 0x96, 0x55, 0xa9, 0x43, 0x99, 0x4f,
	0x38, 0xbc, 0x8b, 0x4c, 0x39, 0xfc, 0x7b, 0xba, 0x92, 0x12, 0x90, 0xb9, 0x1c, 0x4f, 0x85, 0xf5,
	0x7d, 0xb0, 0x10, 0x13, 0x16, 0xb8, 0xd4, 0x33, 0x16, 0xea, 0xda, 0x66, 0xb9, 0xf5, 0xe8, 0x8a,
	0x43, 0x6d, 0xc8, 0xe1, 0xc2, 0x89, 0x1c, 0x27, 0x1c, 0x66, 0x8e, 0x94, 0xc3, 0x65, 0x85, 0x95,
	0x03, 0x64, 0x66, 0x92, 0xde, 0x01, 0xe5, 0x33, 0xec, 0xd9, 0xef, 0x5c, 0x3b, 0xec, 0x1b, 0xbf,
	0x0b, 0xd2, 0x8e, 0x22, 0x95, 0x5b, 0x99, 0x90, 0x70, 0x38, 0x71, 0xa5, 0x1c, 0x56, 0x25, 0x6d,
	0x3c, 0x42, 0xe6, 0x44, 0xd6, 0xb7, 0x40, 0x9e, 0x06, 0x46, 0x59, 0xa0, 0xfe, 0x51, 0xa8, 0xfc,
	0xab, 0x20, 0xe1, 0x30, 0x4f, 0x83, 0x94, 0xc3, 0xb2, 0x0c, 0xd3, 0x00, 0x99, 0x79, 0x1a, 0xe8,
	0x4f, 0x41, 0x11, 0x33, 0xab, 0x6f, 0x00, 0x11, 0xf8, 0x57, 0x05, 0x8a, 0x7b, 0xcc, 0x1a, 0xad,
	0x15, 0x5a, 0xca, 0x61, 0x45, 0x86, 0x46, 0x27, 0x64, 0x8a, 0xa1, 0x7e, 0x0a, 0x16, 0xad, 0xc8,
	0xc6, 0xbd, 0xec, 0x1a, 0x2a, 0x02, 0xb0, 0xab, 0x00, 0x95, 0x76, 0x64, 0xe3, 0xc9, 0x55, 0x4c,
	0x59, 0x53, 0x0e, 0x57, 0xd5, 0x5b, 0x7c, 0x6b, 0x8a, 0xcc, 0x8a, 0x35, 0xc9, 0xe8, 0xef, 0x35,
	0xf0, 0x97, 0x17, 0xbb, 0xb6, 0x8b, 0x7b, 0x36, 0x73, 0x63, 0xc2, 0xc6, 0x8b, 0x16, 0xc5, 0xa2,
	0xd7, 0x6a, 0xd1, 0xea, 0x91, 0x30, 0x3d, 0x13, 0x9e, 0xc9, 0xc2, 0xf9, 0xd9, 0x94, 0xc3, 0x0d,
	0xb9, 0x79, 0xae, 0x8c, 0xcc, 0x55, 0x6f, 0x96, 0xd6, 0x3a, 0xba, 0x1a, 0xd6, 0xb4, 0xeb, 0x61,
	0x4d, 0xfb, 0x31, 0xac, 0x69, 0x1f, 0x6f, 0x6a, 0xb9, 0xeb, 0x9b, 0x5a, 0xee, 0xdb, 0x4d, 0x2d,
	0xf7, 0xe6, 0x89, 0xe3, 0x86, 0xfd, 0xe8, 0xac, 0x61, 0xd1, 0x41, 0x33, 0xf0, 0xfb, 0x84, 0x51,
	0x6f, 0xdf, 0xf6, 0x9a, 0xe2, 0x1f, 0xb9, 0x85, 0x7d, 0x77, 0xeb, 0x2d, 0x65, 0xe7, 0x4d, 0x87,
	0x4e, 0x7d, 0x23, 0xcf, 0x4a, 0xe2, 0xbb, 0xf8, 0xf8, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2f,
	0x0c, 0x69, 0xe3, 0xeb, 0x05, 0x00, 0x00,
}

func (m *NodeResources) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeResources) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NodeResources) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NvidiaDriverVersion) > 0 {
		i -= len(m.NvidiaDriverVersion)
		copy(dAtA[i:], m.NvidiaDriverVersion)
		i = encodeVarintResources(dAtA, i, uint64(len(m.NvidiaDriverVersion)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.CudaVersion) > 0 {
		i -= len(m.CudaVersion)
		copy(dAtA[i:], m.CudaVersion)
		i = encodeVarintResources(dAtA, i, uint64(len(m.CudaVersion)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.Arch) > 0 {
		i -= len(m.Arch)
		copy(dAtA[i:], m.Arch)
		i = encodeVarintResources(dAtA, i, uint64(len(m.Arch)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.Os) > 0 {
		i -= len(m.Os)
		copy(dAtA[i:], m.Os)
		i = encodeVarintResources(dAtA, i, uint64(len(m.Os)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Bandwidth) > 0 {
		i -= len(m.Bandwidth)
		copy(dAtA[i:], m.Bandwidth)
		i = encodeVarintResources(dAtA, i, uint64(len(m.Bandwidth)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Version) > 0 {
		i -= len(m.Version)
		copy(dAtA[i:], m.Version)
		i = encodeVarintResources(dAtA, i, uint64(len(m.Version)))
		i--
		dAtA[i] = 0x3a
	}
	{
		size, err := m.VolumesMounted.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintResources(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size, err := m.VolumesAttached.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintResources(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size, err := m.EphemeralStorage.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintResources(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.GPU.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintResources(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Memory.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintResources(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.CPU.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintResources(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintResources(dAtA []byte, offset int, v uint64) int {
	offset -= sovResources(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *NodeResources) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CPU.Size()
	n += 1 + l + sovResources(uint64(l))
	l = m.Memory.Size()
	n += 1 + l + sovResources(uint64(l))
	l = m.GPU.Size()
	n += 1 + l + sovResources(uint64(l))
	l = m.EphemeralStorage.Size()
	n += 1 + l + sovResources(uint64(l))
	l = m.VolumesAttached.Size()
	n += 1 + l + sovResources(uint64(l))
	l = m.VolumesMounted.Size()
	n += 1 + l + sovResources(uint64(l))
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovResources(uint64(l))
	}
	l = len(m.Bandwidth)
	if l > 0 {
		n += 1 + l + sovResources(uint64(l))
	}
	l = len(m.Os)
	if l > 0 {
		n += 1 + l + sovResources(uint64(l))
	}
	l = len(m.Arch)
	if l > 0 {
		n += 1 + l + sovResources(uint64(l))
	}
	l = len(m.CudaVersion)
	if l > 0 {
		n += 1 + l + sovResources(uint64(l))
	}
	l = len(m.NvidiaDriverVersion)
	if l > 0 {
		n += 1 + l + sovResources(uint64(l))
	}
	return n
}

func sovResources(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozResources(x uint64) (n int) {
	return sovResources(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *NodeResources) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowResources
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeResources: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeResources: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CPU", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResources
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthResources
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthResources
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CPU.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memory", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResources
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthResources
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthResources
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Memory.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GPU", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResources
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthResources
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthResources
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GPU.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EphemeralStorage", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResources
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthResources
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthResources
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.EphemeralStorage.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VolumesAttached", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResources
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthResources
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthResources
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VolumesAttached.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VolumesMounted", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResources
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthResources
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthResources
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VolumesMounted.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResources
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthResources
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthResources
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bandwidth", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResources
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthResources
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthResources
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bandwidth = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Os", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResources
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthResources
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthResources
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Os = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Arch", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResources
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthResources
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthResources
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Arch = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CudaVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResources
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthResources
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthResources
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CudaVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NvidiaDriverVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResources
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthResources
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthResources
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NvidiaDriverVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipResources(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthResources
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipResources(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowResources
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowResources
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowResources
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthResources
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupResources
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthResources
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthResources        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowResources          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupResources = fmt.Errorf("proto: unexpected end of group")
)
